In [ ]:
import pandas as pd
import numpy as np

In [ ]:
match = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IPL_prediction/IPL_Matches_2008_2022.csv")
delivery = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IPL_prediction/IPL_Ball_by_Ball_2008_2022.csv")

In [ ]:
match.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
match.shape

(950, 20)

In [ ]:
delivery.head(10)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
5,1312200,1,0,6,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
6,1312200,1,1,1,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
7,1312200,1,1,2,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
8,1312200,1,1,3,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,4,0,4,0,0,NaN,NaN,NaN,Rajasthan Royals
9,1312200,1,1,4,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [ ]:
delivery.shape

(225954, 17)

In [ ]:
delivery = delivery.merge(match[['ID','Team1','Team2']],left_on='ID',right_on='ID')  #By me

In [ ]:
total_score_df = delivery.groupby(['ID','innings']).sum()['total_run'].reset_index()
total_score_df

<ipython-input-8-d41765ae8c67>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  total_score_df = delivery.groupby(['ID','innings']).sum()['total_run'].reset_index()

           ID  innings  total_run
0      335982        1        222
1      335982        2         82
2      335983        1        240
3      335983        2        207
4      335984        1        129
...       ...      ...        ...
1923  1312198        2        193
1924  1312199        1        157
1925  1312199        2        161
1926  1312200        1        130
1927  1312200        2        133

[1928 rows x 3 columns]

In [ ]:
total_score_df = total_score_df[total_score_df['innings']==1]
total_score_df

           ID  innings  total_run
0      335982        1        222
2      335983        1        240
4      335984        1        129
6      335985        1        165
8      335986        1        110
...       ...      ...        ...
1918  1304116        1        157
1920  1312197        1        188
1922  1312198        1        207
1924  1312199        1        157
1926  1312200        1        130

[950 rows x 3 columns]

In [ ]:
match_df = match.merge(total_score_df[['ID','total_run']],left_on='ID',right_on='ID')
match_df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,130
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,157
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,207
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,188
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,110
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,165
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,129
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,240
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,222

In [ ]:
match_df.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2', 'total_run'],
      dtype='object')

In [ ]:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [ ]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals',
    'Gujarat Titans',
    'Lucknow Super Giants'
    ]

In [ ]:
match_df["Team1"] = match_df["Team1"].str.replace('Delhi Daredevils','Delhi Capitals')
match_df["Team2"] = match_df["Team2"].str.replace('Delhi Daredevils','Delhi Capitals')

match_df["Team1"] = match_df["Team1"].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df["Team2"] = match_df["Team2"].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [ ]:
match_df = match_df[match_df['Team1'].isin(teams)]
match_df = match_df[match_df['Team2'].isin(teams)]

In [ ]:
match_df.shape

(807, 21)

In [ ]:
match_df = match_df[['ID','City','WinningTeam','total_run']]
match_df

          ID        City                  WinningTeam  total_run
0    1312200   Ahmedabad               Gujarat Titans        130
1    1312199   Ahmedabad             Rajasthan Royals        157
2    1312198     Kolkata  Royal Challengers Bangalore        207
3    1312197     Kolkata               Gujarat Titans        188
5    1304115      Mumbai               Mumbai Indians        159
..       ...         ...                          ...        ...
945   335986     Kolkata        Kolkata Knight Riders        110
946   335985      Mumbai  Royal Challengers Bangalore        165
947   335984       Delhi             Delhi Daredevils        129
948   335983  Chandigarh          Chennai Super Kings        240
949   335982   Bangalore        Kolkata Knight Riders        222

[807 rows x 4 columns]

In [ ]:
delivery_df = match_df.merge(delivery,on='ID')
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,Team1,Team2
0,1312200,Ahmedabad,Gujarat Titans,130,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,...,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Rajasthan Royals,Gujarat Titans
1,1312200,Ahmedabad,Gujarat Titans,130,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,...,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Rajasthan Royals,Gujarat Titans
2,1312200,Ahmedabad,Gujarat Titans,130,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,...,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Rajasthan Royals,Gujarat Titans
3,1312200,Ahmedabad,Gujarat Titans,130,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,...,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Rajasthan Royals,Gujarat Titans
4,1312200,Ahmedabad,Gujarat Titans,130,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,...,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,SB Joshi,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192251,335982,Bangalore,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,P Kumar,...,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192252,335982,Bangalore,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,SB Joshi,...,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192253,335982,Bangalore,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,P Kumar,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192254,335982,Bangalore,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,P Kumar,...,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders

In [ ]:
delivery_df = delivery_df[delivery_df['innings']==2]
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,Team1,Team2
120,1312200,Ahmedabad,Gujarat Titans,130,2,0,1,WP Saha,TA Boult,Shubman Gill,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans
121,1312200,Ahmedabad,Gujarat Titans,130,2,0,2,WP Saha,TA Boult,Shubman Gill,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans
122,1312200,Ahmedabad,Gujarat Titans,130,2,0,3,WP Saha,TA Boult,Shubman Gill,...,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans
123,1312200,Ahmedabad,Gujarat Titans,130,2,0,4,Shubman Gill,TA Boult,WP Saha,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans
124,1312200,Ahmedabad,Gujarat Titans,130,2,0,5,Shubman Gill,TA Boult,WP Saha,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,SB Joshi,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192251,335982,Bangalore,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,P Kumar,...,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192252,335982,Bangalore,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,SB Joshi,...,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192253,335982,Bangalore,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,P Kumar,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders
192254,335982,Bangalore,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,P Kumar,...,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders

In [ ]:
delivery_df.shape

(92789, 22)

In [ ]:
delivery_df["current_score"] = delivery_df.groupby('ID').cumsum()['total_run_y']

<ipython-input-21-41b4a70c813b>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  delivery_df["current_score"] = delivery_df.groupby('ID').cumsum()['total_run_y']
<ipython-input-21-41b4a70c813b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df["current_score"] = delivery_df.groupby('ID').cumsum()['total_run_y']

In [ ]:
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,Team1,Team2,current_score
120,1312200,Ahmedabad,Gujarat Titans,130,2,0,1,WP Saha,TA Boult,Shubman Gill,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0
121,1312200,Ahmedabad,Gujarat Titans,130,2,0,2,WP Saha,TA Boult,Shubman Gill,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0
122,1312200,Ahmedabad,Gujarat Titans,130,2,0,3,WP Saha,TA Boult,Shubman Gill,...,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1
123,1312200,Ahmedabad,Gujarat Titans,130,2,0,4,Shubman Gill,TA Boult,WP Saha,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1
124,1312200,Ahmedabad,Gujarat Titans,130,2,0,5,Shubman Gill,TA Boult,WP Saha,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,SB Joshi,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,80
192251,335982,Bangalore,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,P Kumar,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81
192252,335982,Bangalore,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,SB Joshi,...,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81
192253,335982,Bangalore,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,P Kumar,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82
192254,335982,Bangalore,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,P Kumar,...,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82

In [ ]:
delivery_df["runs_left"] = delivery_df["total_run_x"] - delivery_df["current_score"]

<ipython-input-23-9c4cfa74b148>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df["runs_left"] = delivery_df["total_run_x"] - delivery_df["current_score"]

In [ ]:
delivery_df["overs"] = delivery_df["overs"] + 1

<ipython-input-24-3d9af6fe93af>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df["overs"] = delivery_df["overs"] + 1

In [ ]:
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,Team1,Team2,current_score,runs_left
120,1312200,Ahmedabad,Gujarat Titans,130,2,1,1,WP Saha,TA Boult,Shubman Gill,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130
121,1312200,Ahmedabad,Gujarat Titans,130,2,1,2,WP Saha,TA Boult,Shubman Gill,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130
122,1312200,Ahmedabad,Gujarat Titans,130,2,1,3,WP Saha,TA Boult,Shubman Gill,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129
123,1312200,Ahmedabad,Gujarat Titans,130,2,1,4,Shubman Gill,TA Boult,WP Saha,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129
124,1312200,Ahmedabad,Gujarat Titans,130,2,1,5,Shubman Gill,TA Boult,WP Saha,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,15,5,P Kumar,I Sharma,SB Joshi,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,80,142
192251,335982,Bangalore,Kolkata Knight Riders,222,2,15,6,SB Joshi,I Sharma,P Kumar,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141
192252,335982,Bangalore,Kolkata Knight Riders,222,2,15,7,P Kumar,I Sharma,SB Joshi,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141
192253,335982,Bangalore,Kolkata Knight Riders,222,2,16,1,SB Joshi,LR Shukla,P Kumar,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140
192254,335982,Bangalore,Kolkata Knight Riders,222,2,16,2,SB Joshi,LR Shukla,P Kumar,...,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140

In [ ]:
delivery_df["balls_left"] = 126 - (delivery_df['overs']*6 + delivery_df['ballnumber'])

<ipython-input-26-84253939d58d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df["balls_left"] = 126 - (delivery_df['overs']*6 + delivery_df['ballnumber'])

In [ ]:
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,Team1,Team2,current_score,runs_left,balls_left
120,1312200,Ahmedabad,Gujarat Titans,130,2,1,1,WP Saha,TA Boult,Shubman Gill,...,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,119
121,1312200,Ahmedabad,Gujarat Titans,130,2,1,2,WP Saha,TA Boult,Shubman Gill,...,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,118
122,1312200,Ahmedabad,Gujarat Titans,130,2,1,3,WP Saha,TA Boult,Shubman Gill,...,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,117
123,1312200,Ahmedabad,Gujarat Titans,130,2,1,4,Shubman Gill,TA Boult,WP Saha,...,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,116
124,1312200,Ahmedabad,Gujarat Titans,130,2,1,5,Shubman Gill,TA Boult,WP Saha,...,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,15,5,P Kumar,I Sharma,SB Joshi,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,80,142,31
192251,335982,Bangalore,Kolkata Knight Riders,222,2,15,6,SB Joshi,I Sharma,P Kumar,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,30
192252,335982,Bangalore,Kolkata Knight Riders,222,2,15,7,P Kumar,I Sharma,SB Joshi,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,29
192253,335982,Bangalore,Kolkata Knight Riders,222,2,16,1,SB Joshi,LR Shukla,P Kumar,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,29
192254,335982,Bangalore,Kolkata Knight Riders,222,2,16,2,SB Joshi,LR Shukla,P Kumar,...,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,28

In [ ]:
# The columns we required batting team, bowling team, city, run left, ball left,
# wicket left, total_run_x, crr, rrr, result

In [ ]:
delivery_df['player_out'] = delivery_df['player_out'].fillna('0')

<ipython-input-29-a434d2c6e687>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_out'] = delivery_df['player_out'].fillna('0')

In [ ]:
delivery_df['player_out'] = delivery_df['player_out'].apply(lambda x: x if x == '0' else '1')

<ipython-input-30-2ed34709229e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_out'] = delivery_df['player_out'].apply(lambda x: x if x == '0' else '1')

In [ ]:
delivery_df['player_out'] = delivery_df['player_out'].astype('int')

<ipython-input-31-717326d021f6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_out'] = delivery_df['player_out'].astype('int')

In [ ]:
wickets = delivery_df.groupby('ID').cumsum()['player_out'].values

<ipython-input-32-8a226bb22d8a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  wickets = delivery_df.groupby('ID').cumsum()['player_out'].values

In [ ]:
delivery_df['wickets_left'] = 10 - wickets

<ipython-input-33-4bf0c622f20b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['wickets_left'] = 10 - wickets

In [ ]:
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,player_out,kind,fielders_involved,BattingTeam,Team1,Team2,current_score,runs_left,balls_left,wickets_left
120,1312200,Ahmedabad,Gujarat Titans,130,2,1,1,WP Saha,TA Boult,Shubman Gill,...,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,119,10
121,1312200,Ahmedabad,Gujarat Titans,130,2,1,2,WP Saha,TA Boult,Shubman Gill,...,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,118,10
122,1312200,Ahmedabad,Gujarat Titans,130,2,1,3,WP Saha,TA Boult,Shubman Gill,...,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,117,10
123,1312200,Ahmedabad,Gujarat Titans,130,2,1,4,Shubman Gill,TA Boult,WP Saha,...,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,116,10
124,1312200,Ahmedabad,Gujarat Titans,130,2,1,5,Shubman Gill,TA Boult,WP Saha,...,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,15,5,P Kumar,I Sharma,SB Joshi,...,0,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,80,142,31,1
192251,335982,Bangalore,Kolkata Knight Riders,222,2,15,6,SB Joshi,I Sharma,P Kumar,...,0,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,30,1
192252,335982,Bangalore,Kolkata Knight Riders,222,2,15,7,P Kumar,I Sharma,SB Joshi,...,0,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,29,1
192253,335982,Bangalore,Kolkata Knight Riders,222,2,16,1,SB Joshi,LR Shukla,P Kumar,...,0,NaN,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,29,1
192254,335982,Bangalore,Kolkata Knight Riders,222,2,16,2,SB Joshi,LR Shukla,P Kumar,...,1,caught,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,28,0

In [ ]:
delivery_df.columns

Index(['ID', 'City', 'WinningTeam', 'total_run_x', 'innings', 'overs',
       'ballnumber', 'batter', 'bowler', 'non-striker', 'extra_type',
       'batsman_run', 'extras_run', 'total_run_y', 'non_boundary',
       'isWicketDelivery', 'player_out', 'kind', 'fielders_involved',
       'BattingTeam', 'Team1', 'Team2', 'current_score', 'runs_left',
       'balls_left', 'wickets_left'],
      dtype='object')

In [ ]:
delivery_df['crr'] = (delivery_df['current_score']*6)/(120 - delivery_df['balls_left'])

<ipython-input-36-b95617a1e867>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['crr'] = (delivery_df['current_score']*6)/(120 - delivery_df['balls_left'])

In [ ]:
delivery_df['rrr'] = (delivery_df['runs_left']*6)/(delivery_df['balls_left'])

<ipython-input-37-9f4b09bb7637>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['rrr'] = (delivery_df['runs_left']*6)/(delivery_df['balls_left'])

In [ ]:
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,fielders_involved,BattingTeam,Team1,Team2,current_score,runs_left,balls_left,wickets_left,crr,rrr
120,1312200,Ahmedabad,Gujarat Titans,130,2,1,1,WP Saha,TA Boult,Shubman Gill,...,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,119,10,0.000000,6.554622
121,1312200,Ahmedabad,Gujarat Titans,130,2,1,2,WP Saha,TA Boult,Shubman Gill,...,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,118,10,0.000000,6.610169
122,1312200,Ahmedabad,Gujarat Titans,130,2,1,3,WP Saha,TA Boult,Shubman Gill,...,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,117,10,2.000000,6.615385
123,1312200,Ahmedabad,Gujarat Titans,130,2,1,4,Shubman Gill,TA Boult,WP Saha,...,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,116,10,1.500000,6.672414
124,1312200,Ahmedabad,Gujarat Titans,130,2,1,5,Shubman Gill,TA Boult,WP Saha,...,NaN,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,115,10,1.200000,6.730435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,15,5,P Kumar,I Sharma,SB Joshi,...,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,80,142,31,1,5.393258,27.483871
192251,335982,Bangalore,Kolkata Knight Riders,222,2,15,6,SB Joshi,I Sharma,P Kumar,...,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,30,1,5.400000,28.200000
192252,335982,Bangalore,Kolkata Knight Riders,222,2,15,7,P Kumar,I Sharma,SB Joshi,...,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,29,1,5.340659,29.172414
192253,335982,Bangalore,Kolkata Knight Riders,222,2,16,1,SB Joshi,LR Shukla,P Kumar,...,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,29,1,5.406593,28.965517
192254,335982,Bangalore,Kolkata Knight Riders,222,2,16,2,SB Joshi,LR Shukla,P Kumar,...,BB McCullum,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,28,0,5.347826,30.000000

In [ ]:
def result(row):
  return 1 if row['WinningTeam']==row['BattingTeam'] else 0

In [ ]:
delivery_df["result"] = delivery_df.apply(result,axis=1)

<ipython-input-40-3a712f56e65a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df["result"] = delivery_df.apply(result,axis=1)

In [ ]:
delivery_df.head()

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,BattingTeam,Team1,Team2,current_score,runs_left,balls_left,wickets_left,crr,rrr,result
120,1312200,Ahmedabad,Gujarat Titans,130,2,1,1,WP Saha,TA Boult,Shubman Gill,...,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,119,10,0.0,6.554622,1
121,1312200,Ahmedabad,Gujarat Titans,130,2,1,2,WP Saha,TA Boult,Shubman Gill,...,Gujarat Titans,Rajasthan Royals,Gujarat Titans,0,130,118,10,0.0,6.610169,1
122,1312200,Ahmedabad,Gujarat Titans,130,2,1,3,WP Saha,TA Boult,Shubman Gill,...,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,117,10,2.0,6.615385,1
123,1312200,Ahmedabad,Gujarat Titans,130,2,1,4,Shubman Gill,TA Boult,WP Saha,...,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,116,10,1.5,6.672414,1
124,1312200,Ahmedabad,Gujarat Titans,130,2,1,5,Shubman Gill,TA Boult,WP Saha,...,Gujarat Titans,Rajasthan Royals,Gujarat Titans,1,129,115,10,1.2,6.730435,1

In [ ]:
delivery_df['BowlingTeam'] = delivery_df.apply(lambda row: row['Team2'] if row['BattingTeam'] == row['Team1'] else row['Team1'], axis=1)

<ipython-input-42-1f343f546800>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['BowlingTeam'] = delivery_df.apply(lambda row: row['Team2'] if row['BattingTeam'] == row['Team1'] else row['Team1'], axis=1)

In [ ]:
delivery_df

,ID,City,WinningTeam,total_run_x,innings,overs,ballnumber,batter,bowler,non-striker,...,Team1,Team2,current_score,runs_left,balls_left,wickets_left,crr,rrr,result,BowlingTeam
120,1312200,Ahmedabad,Gujarat Titans,130,2,1,1,WP Saha,TA Boult,Shubman Gill,...,Rajasthan Royals,Gujarat Titans,0,130,119,10,0.000000,6.554622,1,Rajasthan Royals
121,1312200,Ahmedabad,Gujarat Titans,130,2,1,2,WP Saha,TA Boult,Shubman Gill,...,Rajasthan Royals,Gujarat Titans,0,130,118,10,0.000000,6.610169,1,Rajasthan Royals
122,1312200,Ahmedabad,Gujarat Titans,130,2,1,3,WP Saha,TA Boult,Shubman Gill,...,Rajasthan Royals,Gujarat Titans,1,129,117,10,2.000000,6.615385,1,Rajasthan Royals
123,1312200,Ahmedabad,Gujarat Titans,130,2,1,4,Shubman Gill,TA Boult,WP Saha,...,Rajasthan Royals,Gujarat Titans,1,129,116,10,1.500000,6.672414,1,Rajasthan Royals
124,1312200,Ahmedabad,Gujarat Titans,130,2,1,5,Shubman Gill,TA Boult,WP Saha,...,Rajasthan Royals,Gujarat Titans,1,129,115,10,1.200000,6.730435,1,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192250,335982,Bangalore,Kolkata Knight Riders,222,2,15,5,P Kumar,I Sharma,SB Joshi,...,Royal Challengers Bangalore,Kolkata Knight Riders,80,142,31,1,5.393258,27.483871,0,Kolkata Knight Riders
192251,335982,Bangalore,Kolkata Knight Riders,222,2,15,6,SB Joshi,I Sharma,P Kumar,...,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,30,1,5.400000,28.200000,0,Kolkata Knight Riders
192252,335982,Bangalore,Kolkata Knight Riders,222,2,15,7,P Kumar,I Sharma,SB Joshi,...,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,29,1,5.340659,29.172414,0,Kolkata Knight Riders
192253,335982,Bangalore,Kolkata Knight Riders,222,2,16,1,SB Joshi,LR Shukla,P Kumar,...,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,29,1,5.406593,28.965517,0,Kolkata Knight Riders
192254,335982,Bangalore,Kolkata Knight Riders,222,2,16,2,SB Joshi,LR Shukla,P Kumar,...,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,28,0,5.347826,30.000000,0,Kolkata Knight Riders

In [ ]:
final_df = delivery_df[[ 'BattingTeam', 'BowlingTeam', 'City', 'runs_left', 'balls_left',
 'wickets_left', 'total_run_x', 'crr', 'rrr', 'result']]

In [ ]:
final_df.head()

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_left,total_run_x,crr,rrr,result
120,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,119,10,130,0.0,6.554622,1
121,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,118,10,130,0.0,6.610169,1
122,Gujarat Titans,Rajasthan Royals,Ahmedabad,129,117,10,130,2.0,6.615385,1
123,Gujarat Titans,Rajasthan Royals,Ahmedabad,129,116,10,130,1.5,6.672414,1
124,Gujarat Titans,Rajasthan Royals,Ahmedabad,129,115,10,130,1.2,6.730435,1

In [ ]:
final_df = final_df.sample(final_df.shape[0])
final_df.head()

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_left,total_run_x,crr,rrr,result
159307,Deccan Chargers,Mumbai Indians,Mumbai,55,32,3,172,7.977273,10.312500,0
129406,Kings XI Punjab,Deccan Chargers,Chandigarh,171,100,9,190,5.700000,10.260000,1
64785,Kings XI Punjab,Kolkata Knight Riders,Kolkata,75,63,10,191,12.210526,7.142857,1
83591,Kolkata Knight Riders,Delhi Daredevils,Kolkata,16,45,9,98,6.560000,2.133333,1
77168,Delhi Daredevils,Sunrisers Hyderabad,Raipur,96,66,9,158,6.888889,8.727273,1

In [ ]:
final_df["City"].unique()

array(['Mumbai', 'Chandigarh', 'Kolkata', 'Raipur', 'Delhi',
       'Visakhapatnam', 'Cape Town', 'Bangalore', 'Chennai', 'Abu Dhabi',
       'Pune', 'Hyderabad', 'Indore', 'Kimberley', 'Sharjah',
       'Johannesburg', 'Port Elizabeth', 'Jaipur', 'Dharamsala', 'Dubai',
       'Ahmedabad', 'Bloemfontein', 'Durban', 'Navi Mumbai', 'Centurion',
       'Bengaluru', 'Nagpur', 'Cuttack', 'Ranchi', 'East London'],
      dtype=object)

In [ ]:
final_df.isnull().sum()

BattingTeam        0
BowlingTeam        0
City            6012
runs_left          0
balls_left         0
wickets_left       0
total_run_x        0
crr                0
rrr               12
result             0
dtype: int64

In [ ]:
final_df.dropna(inplace=True)

In [ ]:
final_df.sample()

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_left,total_run_x,crr,rrr,result
5410,Kolkata Knight Riders,Rajasthan Royals,Mumbai,149,118,10,152,9.0,7.576271,1

In [ ]:
final_df = final_df[final_df['balls_left']!= 0]

In [ ]:
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
x_train.shape

(69189, 9)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [ ]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['BattingTeam','BowlingTeam', 'City'])
], remainder='passthrough')

In [ ]:
pipe = Pipeline(steps = [
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [ ]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['BattingTeam', 'BowlingTeam',
                                                   'City'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [ ]:
y_pred = pipe.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.8103248930512198

In [ ]:
pipe.predict_proba(x_test)[1]

array([0.94271101, 0.05728899])

In [ ]:
import pickle
pickle.dump(pipe,open('IPL_Preditor.pkl','wb'))

In [ ]:
# def match_progression(x_df,match_id,pipe):
#     match = x_df[x_df['ID'] == match_id]
#     match = match[(match['ballnumber'] == 6)]
#     temp_df = match[['BattingTeam','BowlingTeam','City','runs_left','balls_left','wickets_left','total_run_x','crr','rrr']].dropna()
#     temp_df = temp_df[temp_df['balls_left'] != 0]
#     result = pipe.predict_proba(temp_df)
#     temp_df['lose'] = np.round(result.T[0]*100,1)
#     temp_df['win'] = np.round(result.T[1]*100,1)
#     temp_df['end_of_over'] = range(1,temp_df.shape[0]+1)

#     target = temp_df['total_runs_x'].values[0]
#     runs = list(temp_df['runs_left'].values)
#     new_runs = runs[:]
#     runs.insert(0,target)
#     temp_df['runs_after_over'] = np.array(runs)[:-1] - np.array(new_runs)
#     wickets = list(temp_df['wickets'].values)
#     new_wickets = wickets[:]
#     new_wickets.insert(0,10)
#     wickets.append(0)
#     w = np.array(wickets)
#     nw = np.array(new_wickets)
#     temp_df['wickets_in_over'] = (nw - w)[0:temp_df.shape[0]]

#     print("Target-",target)
#     temp_df = temp_df[['end_of_over','runs_after_over','wickets_in_over','lose','win']]
#     return temp_df,target

In [ ]:
# temp_df,target = match_progression(delivery_df,74,pipe)
# temp_df

In [ ]:
# import matplotlib.pyplot as plt
# plt.figure(figsize=(18,8))
# plt.plot(temp_df['end_of_over'],temp_df['wickets_in_over'],color='yellow',linewidth=3)
# plt.plot(temp_df['end_of_over'],temp_df['win'],color='#00a65a',linewidth=4)
# plt.plot(temp_df['end_of_over'],temp_df['lose'],color='red',linewidth=4)
# plt.bar(temp_df['end_of_over'],temp_df['runs_after_over'])
# plt.title('Target-' + str(target))